/// Flutter icons FA5_Pets
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FA5_Pets
///      fonts:
///       - asset: fonts/FA5_Pets.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FA5Pets {
  FA5Pets._();

  static const _kFontFam = 'FA5_Pets';
  static const String? _kFontPkg = null;

  static const IconData cat =
      IconData(0xf6be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog =
      IconData(0xf6d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
